- Makefile
- package.json
- server/app.js
- server/middleware/log-request.js
- test/smoke.js
Reverts Financial-Times/next-syndication-api#15
> Revert "Update core deps"

- .gitignore
- server/controllers/resolve.js
- server/lib/enrich/index.js
- server/lib/enrich/package.js
- server/lib/resolve/messageCode.js
> make packages syndicatable

- .gitignore
- worker/crons/redshift/callback.js
> fix remove quotes

- worker/crons/redshift/callback.js
> strip out any newlines

- worker/crons/redshift/callback.js
> strip out carriage returns

- server/lib/get-history-by-contract-id.js
> get content_area from db for spanish

- server/lib/get-salesforce-contract-by-id.js
- test/server/lib/get-salesforce-contract-by-id.spec.js
> Return stubbed contracts before calling Salesforce

- flags/syndicationMigrationComplete.json
- server/middleware/check-if-new-syndication-user.js
- server/middleware/expedite-user-auth.js
- test/server/middleware/check-if-new-syndication-user.spec.js
Reverts Financial-Times/next-syndication-api#69
> Revert "remove syndicationMigrationComplete flag usage"

- health/error-spikes.js
- package.json
- server/app.js
> add 401 spike healthcheck

- health/db-sync-state.js
PR to attempt to fix the healthcheck status before alerting a failure. Closes #68 
🐿 v2.7.0
> attempt to reload tables if healthcheck fails

- server/middleware/get-contract-by-id.js
- server/middleware/get-users-for-licence.js
> log the licence id on some errors

- server/controllers/resolve.js
Getting a fair amount of these errors being logged, would be good to know where they're coming from
🐿 v2.7.0
> add referer to error logs

- server/init.js
> Extra logging for unhandled

- README.md
- health/sqs.js
- server/lib/get-contract-by-id.js
> Add instructions and allow to run locally

- README.md
- health/sqs.js
> Updated readme and health sqs test

- server/lib/reformat-salesforce-contract.js
Rather than throw an error when an addendum doesn't have a matching asset, just log it
🐿 v2.10.2
> Dont throw, log

- README.md
> Add customer support email

- server/init.js
> Change logging for unhandled rejections

- server/lib/enrich/video.js
> Handle videos without attachments

- package.json
> Update jsonpath to secure version

- server/controllers/backup.js
- server/controllers/legacy_downloads.js
- server/controllers/migrate.js
- server/controllers/redshift.js
- server/controllers/reload.js
- server/middleware/masquerade.js
Remove superdooperstormtrooperuser as there are none and its just silly
> Remove superdooperstormtrooperuser

- server/controllers/backup.js
- server/controllers/export.js
- server/controllers/get-contract-by-id.js
- server/controllers/history.js
- server/controllers/legacy_downloads.js
- server/controllers/migrate.js
- server/controllers/redshift.js
- server/controllers/reload.js
- server/controllers/update-download-format.js
- server/controllers/user-status.js
- server/lib/enrich/index.js
add route to controller logs
fix dodgy type check
> @maxcbc/further log updates

- server/middleware/db.js
> Catch when db connection fails

- server/lib/get-content-by-id.js
> Add logging to add-logging-to-get-content-by-id-errors

- .circleci/config.yml
- package.json
- server/init.js
- server/lib/get-content-by-id.js
> Dont long unhandled promise when rejected (only reason)

- server/controllers/get-content-by-id.js
> Catch get content by id errors

- server/lib/enrich/index.js
> Revert enrich type check

- package.json
Reverts Financial-Times/next-syndication-api#119
> Revert "Update dependency massive to v5"

- .circleci/config.yml
- runbook.md
[ ] this could still do with a architecture description
> Runbooksmd

- package.json
- server/controllers/export.js
- server/controllers/reload.js
- server/controllers/translations.js
- server/lib/get-all-existing-items-for-contract.js
- server/lib/get-history-by-contract-id.js
- test/fixtures/massive.js
- test/server/controllers/translations.spec.js
- test/server/lib/get-all-existing-items-for-contract.spec.js
- test/server/lib/get-history-by-contract-id.spec.js
- test/server/middleware/expedite-user-auth.spec.js
https://trello.com/c/iYjtQsKc/1313-syndication-api-massive-package-upgrade
> update massive to 5.x

- README.md
Findings from investigation into this issue (which this documentation will hopefully prevent anyone repeating): https://financialtimes.atlassian.net/jira/software/projects/NOPSCOPS/boards/952?selectedIssue=NOPSCOPS-124.
> Update README to include details about article `canBeSyndicated` property

- README.md
Clarifying note following @andygout and @binaryberry's meeting with Richard Pigden (Head of Adhoc Sales and Republishing Coordinator).
> Add README detail to canBeSyndicated verify description

- health/error-spikes.js
See analysis in [NOPSCOPS-224][NOPSCOPS-224]
* increased threshold from 0.10 to 0.25
* increased sample period from 20 to 60 minutes
[NOPSCOPS-224]: https://financialtimes.atlassian.net/browse/NOPSCOPS-224
> NOPSCOPS-224 Alert for 401 rate: increase threshold and sample period

- CODEOWNERS
- runbook.md
> chore: assign ownership to Accounts team

- server/app.js
- Healthchecks aren't showing up in [Heimdall](https://heimdall.in.ft.com/system?code=next-syndication-api#monitored-checks-list).
- The fix involves unrolling a nested array and concatenating it with the existing healtchecks.
> Fix broken healthchecks 🐿 v2.12.6

- health/middlewares.js
- Remove unnecessary duplicate health check. 
- Clear up some language conventions.
> Remove duplicate healthcheck 🐿 v2.12.6

- server/middleware/check-if-new-syndication-user.js
- server/middleware/decode-session.js
- server/middleware/expedite-user-auth.js
- server/middleware/is-syndication-user.js
Its very difficult to trace a user through the middleware operations - this is a start to adding more expansive logs to the application
> chore: add tracing logs 🐿 v2.13.0

- runbook.md
The PR updates the runbook with architecture diagram link
> ACC-521 Update runbook with architecture diagram link

- server/controllers/download-by-content-id.js
- server/helpers/is-download-disabled.js
- test/server/helpers/is-download-disabled.spec.js
This PR adds user permission check before content can be downloaded
> feat: check user permissions for downloads

- package.json
The PR bump package version to 0.33.0
> Bump package version to 0.33.0

- package.json
- test/server/lib/download/podcast.spec.js
- test/server/lib/download/video.spec.js
Reverts Financial-Times/next-syndication-api#219
> Revert "Update dependency archiver to v5"

- runbook.md
Jira card: [NOPS-331](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1137&projectKey=NOPS&modal=detail&selectedIssue=NOPS-331).
> Update Runbook "Supported By" team to customer-products-ops-cops

- server/lib/enrich/article.js
- test/server/lib/enrich/index.js
This PR adds `hasGraphics` property when enriching content
> feat: add has graphics when enriching

- package.json
Reverts Financial-Times/next-syndication-api#272
> Revert "Update dependency n-health to v5"

- package.json
- server/controllers/download-by-content-id.js
- server/lib/download/article.js
Creating graphite metrics for Syndication article and video downloads
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1108?modal=detail&selectedIssue=ACC-1347)
> ACC-1347 Create metrics for syndication article and video downloads

- health/db-backups.js
Add an ID property to the database health check, to give us check history in Heimdall.
N/A - happy to let this get deployed with the next release
N/A - happy to let this get deployed with the next release
> Add id property to database healthcheck

- package-lock.json
- package.json
- queue/message-queue-event.js
- worker/crons/tidy-bucket/callback.js
add log to publish message queue event
[ticket](https://financialtimes.atlassian.net/browse/ACC-1709)
0.41.3
> Acc 1709 add log publish queue

- package-lock.json
- package.json
- server/init.js
improve the Splunk error logs for the application ,Using Reliability Kit error logging middleware for Express ..
https://financialtimes.atlassian.net/browse/ACC-1863
> ACC-1863 Implement Quick win #1

- README.md
- package-lock.json
This PR is improving the documentation of running `next-syndication-api` locally and fixing any of 403s we get in sending a request to `next-syndication-api` locally.
[Jira ticket](https://financialtimes.atlassian.net/browse/ACC-1870)
> ACC-1870-Update Documentation

- runbook.md
As per Step 3 of the [Heroku log drains Migration Guide](https://financialtimes.atlassian.net/wiki/spaces/DS/pages/7883555001/Migrating+an+app+to+Heroku+log+drains).
[CPREL-365](https://financialtimes.atlassian.net/jira/software/c/projects/CPREL/boards/1426?modal=detail&selectedIssue=CPREL-365)
N/A
N/A
> Update Splunk queries

- server/lib/get-history-by-contract-id.js
adding fail safe to handle: https://financialtimes.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22heroku%22%20source%3D%22next-syndication-api%22%20%20level%3D%22error%22%7C%20spath%20%22error.message%22%20%7C%20search%20%22error.message%22%3D%22function%20syndication.get_content_es_by_id(unknown)%20does%20not%20exist%22&earliest=-7d%40h&latest=now&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&display.events.timelineEarliestTime=1669204800&display.events.timelineLatestTime=1669219200&sid=1669217023.10419494
> add fail safe for get history by contract id

- package-lock.json
- package.json
- server/lib/get-contract-by-id.js
Add licence_id to log with null assets contract
0.41.11
> add licence_id to logs

- doc/no-syndication-icons-debugging.md
- runbook.md
Improved documentation on how to debug missing syndication icons. 
**Please note this commit has been committed with `--no-verify` because Secret Squirrel has been running in circles. Secret Squirrel is due to be sun-set later this year and `no-verify` has been the [recommended approach](https://financialtimes.slack.com/archives/C02HH3JAQ5V/p1683637233011969?thread_ts=1683631856.341499&cid=C02HH3JAQ5V)**
https://financialtimes.atlassian.net/browse/ACC-2286
doesn't apply - doc update
> ACC-2286 extended and cleaned up documentation about debugging missing icons

- README.md
- doc/README.md
- doc/SYNDICATION.md
Updating wiki links in the repo code to point to the new ones in confluence
> Update wiki links

- worker/crons/redshift/callback.js
Hello team,
daily we get some files from the next-syndication-db-backups bucket to process:
Last ones were loaded on 08.09, so I want to check if there is some issue.
These are the ones we expect: contract_data.YYYY-MM-DD, downloads.YYYY-MM-DD , saved_items.YYYY-MM-DD . Thanks :raised_hands::skin-tone-4:
> ACC-2535: Add defensive code

- worker/crons/redshift/callback.js
> ACC-2535: add upload error log

- worker/crons/redshift/callback.js
Add more logs to tracing redshift process
> ACC-2535: add more logs to tracing

- worker/crons/redshift/callback.js
> Acc 2535 add more logs

- worker/crons/redshift/callback.js
Fix redshift cronjob backup changing asyn code related with file creation
> ACC-2535: send file when readstream finish

- package-lock.json
- package.json
This was missed in previous releases
> Fix the version number in the package

- package-lock.json
- package.json
Reverts Financial-Times/next-syndication-api#479
> Revert "Fix the version number in the package"

- README.md
This PR updates the documentation with more information on how to get the API key for sending email.
[Jira ticket](https://financialtimes.atlassian.net/browse/ACC-2928)
> chore: Update README to explain how to obtain the EMAIL_PLATFORM_API_KEY

- package-lock.json
- package.json
This PR is to update the dependencies so they support node 22.x
[LIF-30](https://financialtimes.atlassian.net/browse/LIF-30)
N/A
[LIF-30]: https://financialtimes.atlassian.net/browse/LIF-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update dep to support node v22

- .circleci/config.yml
- .toolkitrc.yml
- package-lock.json
- package.json
Upgrade node to v22 and npm to v10
[LIF-101](https://financialtimes.atlassian.net/browse/LIF-101)
v3.0.1
[LIF-101]: https://financialtimes.atlassian.net/browse/LIF-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update node to 22

- package-lock.json
- package.json
- server/controllers/download-by-content-id.js
- server/controllers/get-content-by-id.js
- server/controllers/save-by-content-id.js
- server/controllers/unsave-by-content-id.js
- server/lib/builders/document-builder.js
- server/lib/download/index.js
- server/lib/enrich/article.js
- server/lib/enrich/index.js
- server/lib/enrich/package.js
- server/lib/enrich/podcast.js
- server/lib/enrich/video.js
- server/lib/get-content-by-id.js
- server/lib/get-contract-by-id.js
- server/middleware/get-contract-by-id-from-session.js
- server/middleware/get-syndication-licence-for-user.js
- test/server/controllers/download-by-content-id.spec.js
- test/server/lib/download/index.spec.js
- test/server/middleware/get-syndication-licence-for-user.spec.js
This PR removes the `graphicSyndication` flag and turn the feature to a permanent feature and remove any conditional code/rendering that was based on this flag
[Jira Ticket](https://financialtimes.atlassian.net/browse/LIF-580)
Draft PR in next-syndication-dl https://github.com/Financial-Times/next-syndication-dl/pull/208
> LIF-580: Remove graphic syndication flag
