- server/lib/resolve/canDownload.js
- test/server/lib/resolve/canDownload.spec.js
The assets' legacy download count wasn't being taken into account when calculated whether a contract had run out of content to download. This meant that some users were incorrectly able to download more content that their contract allowed, despite running out.
🐿 v2.5.16
> correct downloaded count

- worker/crons/redshift/callback.js
When building up the redshift csv file, Titles that included double quotes were ending the string so we are just stripping out any quotes from the title
🐿 v2.5.16
> remove double quotes

- schema/message-v1.json
- server/lib/resolve/messageCode.js
- test/server/lib/resolve/messsageCode.spec.js
- test/worker/sync/db-persist/spoor-publish.spec.js
We have been sending a MSG_2000 code for content even if it wasn't downloadable on the contract. This adds a check to ensure the user can download. 
🐿 v2.5.16
> correct MSG_2000 logic

- package.json
This is predominantly for upgrading dependant services eg, https://github.com/Financial-Times/next-syndication-dl/blob/master/package.json#L10, allowing them to [upgrade deps](https://github.com/Financial-Times/next-syndication-api/pull/96).
See https://trello.com/c/rLcIbPr4/425-ensure-that-no-apps-are-still-reading-from-the-old-graphite-server
> Bump api version

- package.json
- test/fixtures/massive.js
- test/server/lib/prepare-download-response.spec.js
- test/worker/crons/migration/callback.spec.js
See https://trello.com/c/PE5Redty/476-upgrading-sinon-for-security-fixes-makes-syndication-api-tests-fail-stubs-need-done-a-different-way
> Upgrade sinon for security fixes

- server/app.js
This syntax threw me so I've tweaked it to make it easier to understand.
This PR uses an explicit new array `contractsMiddleware` rather
than creating a scope so we can reuse the same variable `middleware`
This PR also deletes some commented out routes.
🐿 v2.10.3
> Tidy up app.js

- server/app-dl.js
- server/app.js
See financial-times/n-express#563 for details.
This change requires n-express@19.22 to work but can be safely merged without it
> add graphiteName field to n-express options

- health/error-spikes.js
The 401 error spike alert goes off quite often - after looking into it, it seems that as there is low traffic to the service, even a single visit to https://www.ft.com/republishing/contract by a non-syndicated user will generate an alert.
I'm not sure what the level should be; however updating the proportion to 10% of all requests might be an improvement.
> Increasing the Threshold for 401 error spike alerts

- runbook.md
There were two health check links under the HealthCheck header both of these pages point to the same health check so I have decided to remove ft-next-syndication-api-https
This health check page will then be deleted from biz-ops
> Removes ft-next-syndication-api-https

- health/error-spikes.js
Updates the 401 responses healthcheck for the next-syndiation-api to include a `samplePeriod` parameter.
The threshold for this alert is currently set to 10%, which ordinarily would be very high, but we commonly receive between 1 and 4 requests per minute to the syndication-api, meaning a single 401 can easily trigger this alert.
Adding a `samplePeriod` parameter to the healthcheck should mitigate the effects of single 401 responses and trigger an alert only when there is a genuine problem with the app. This will help ops-cops to identify and respond to genuine errors more efficiently.
[ops-cops ticket](https://financialtimes.atlassian.net/jira/software/projects/NOPSCOPS/boards/952)
> adds a samplePeriod parameter to the 401 reponses healthcheck 🐿 v2.12.5

- health/error-spikes.js
See similar PR #188 
Jira [NOPSCOPS-224](https://financialtimes.atlassian.net/browse/NOPSCOPS-224)
From a look at the data, the alarm **"401 rate for articles is acceptable, severity 1 issue"** was cause by only a couple of 401 response during the 15 minutes sample, which caused the 10% threshold to be surpassed due to low traffic.
Similarly to what was done in #188, this PR increases the `samplePeriod` from 15 to 20 minutes to reduce the impact of these 401s when the traffic is low.
> NOPSCOSP-224 Increase the sample period to 20 minutes

- server/app.js
- Require statement was incorrectly imported twice.
> Fix healthchecks typo 🐿 v2.12.6

- health/middlewares.js
- Remap `api.ft.com` and `next-session.ft.com` healthchecks to their underlying services. 
- Fixes silently failing healthchecks.
> Map healthcheck URLs to underlying services 🐿 v2.12.6

- config/default.yaml
- Bump up the threshold for how many messages can be in the queue at any one time.
> Increase SQS healthcheck threshold 🐿 v2.12.6

- health/error-spikes.js
The `sumSeries` function in Graphite only returns ["the sum at **each** datapoint"](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.sumSeries), rather than summing all data points over a certain sample period. 
So if one 401 and one 200 are returned at the same time (as happened this afternoon in the graph below), this healthcheck will fail as crosses the threshold with a 50% failure rate.
To fix this we instead need to use the `summarize` function to sum all data points over a certain time.
> Change 401 healthcheck metric

- README.md
Wiki has a bit more info about Syndication and isn't the most obvious place to look, so people on OpsCops might struggle to find the info they need.
> Added link to Wiki

- package.json
- server/lib/decorate-article.js
- server/lib/handlebars.js
- test/server/lib/handlebars.spec.js
- worker/sync/db-persist/mail-contributor.js
Since this project was only using the exported `handlebars` method from `n-handlebars` which was essentially just the regular `handlebars` module you can fin in NPM, I removed it and replaced it for regular the `handlebars` module.
The only extended helper being used on the project is #ifEquals so I added that helper as well to the regular `handlebars` module.
I also added unit tests to test the newly added handlebars code.
> Remove Handlebars

- package.json
- server/app.js
This PR updates [n-internal-tools](https://github.com/Financial-Times/n-internal-tool) from `3.0.0` to `4.0.0`
**Version 4.0.0** removes s30 middleware from n-internal-tool  [#35](https://github.com/Financial-Times/n-internal-tool/pull/35)
**Version 5.0.0** Adds .o-grid-container--snappy class  [#36](https://github.com/Financial-Times/n-internal-tool/pull/39)
**Version 6.0.0**   Removes n-handlebars and uses express-handlebars
**Version 7.0.0**   Stable release
> ACC-530 chore: update n-internal-tools

- package.json
This PR bumps `next-syndication-api` version to 0.32.0 to match release tag.
> Bump `next-syndication-api` version to 0.32.0

- server/controllers/download-by-content-id.js
- server/helpers/is-download-disabled.js
- test/server/helpers/is-download-disabled.spec.js
Users with a licence that can download paid content should have contributor_content as true.
However, contributor_content should have be gotten from res.local.contract that is defined [here](https://github.com/Financial-Times/next-syndication-api/blob/master/server/middleware/get-contract-by-id-from-param.js#L12) not res.local.user.
> fix: Inc 697 - Syndication users unable to download paid for content

- package.json
This PR bumps syndication-api to version 0.33.2
> chore: Bump version to 0.33.2

- secret-squirrel.js
- server/lib/enrich/article.js
- server/lib/resolve/canAllGraphicsBeSyndicated.js
- server/lib/resolve/hasGraphics.js
- server/lib/resolve/index.js
- server/lib/syndicate-content.js
- test/fixtures/content/42ad255a-99f9-11e7-b83c-9588e51488a0.json
- test/fixtures/content/a1af0574-eafb-41bd-aa4f-59aa2cd084c2.json
- test/fixtures/content/b16fce7e-3c92-48a3-ace0-d1af3fce71af.json
- test/fixtures/content/ef4c49fe-980e-11e7-b83c-9588e51488a0.json
- test/fixtures/content/items.json
- test/server/controllers/resolve.spec.js
- test/server/lib/enrich/article.js
https://financialtimes.atlassian.net/browse/ACC-622
- updated some fixtures to their 2020 state (fixtures are used for mocks in tests and have been stuck in their 2017 version). Not all of the fixtures have been updated (see #234 ) because it was out of scope for this ticket. 
- the endpoint now returns `hasGraphics` boolean and `canAllGraphicsBeSyndicated` boolean *for article only*
Currently we don't have an article that has `canAllGraphicsBeSyndicated` `true`, and I'm not sure what's the practicality of having a test for something that is different in prod.
> ACC-622 Enhance response to include info about Graphic syndication

- server/lib/enrich/article.js
It was reported to Ops Cop that the syndication icons are missing from
the front page only. We narrowed down the cause to this error:
`Cannot read property 'endsWith' of undefined`. As a fix, we now check
if both `embed` and `embed.type` exist before doing any additional
checks.
> NOPS-431 Fix bug causing syndication icons to go missing

- health/dl-error-spikes.js
- server/app-dl.js
Currently next-syndication-dl doesn't have any healthchecks, so we are not alerted about any spikes in 404s (which are the symptoms of issues such as this one). This healtcheck will help to spot issues ourselves rather than waiting on Customer Care to report this from users.
**Why is this not a "number of successes vs number of failures"?** The number of `200` responses isn't high enough on regular basis for the ratio to be a sensible measure.  
Reasoning for numbers:
severity - 1 - in the incident linked above it was stated that it ended up being a P2 but it should really have been a P1
threshold for 404 - 5 - it feels like 2 or 3 can happen organically every now and again, but anything over 5 would benefit from at least a glance what's happening
threshold for 403 - 1 - not sure about …
> ACC-558 Added spike health check for syndication-dl

- package.json
This PR prepares next-syndication-api for `v0.34.2` release
> chore: release next-syndication-api v0.34.2

- package.json
This PR prepares next-syndication-api for `v0.35.0` release
> chore: release next-syndication-api v0.35.0

- health/sqs.js
There were errors regarding *Graphite Filename too long Alert *
Links: https://financialtimes.splunkcloud.com/en-US/app/search/search?s=%2FservicesNS%2Fnobody%2Fsearch%2Fsaved%2Fsearches%2FGraphite%2520Filename%2520too%2520long%2520Alert&display.page.search.mode=fast&dispatch.sample_ratio=1&workload_pool=&q=search%20index%3Dapp_prod%20source%3D%22%2Fvar%2Flog%2Fgo-carbon%2Fgo-carbon.log%22%20%22ERROR%20%5Bpersister%5D%20failed%20to%20open%20whisper%20file%22%20%20%7C%20rex%20%22%5C%22path%5C%22%3A%20%5C%22%5C%2Fopt%5C%2Fgraphite%5C%2Fstorage%5C%2Fwhisper(%3F%3Cpath%3E%5C%2F%5B%5Cw%5C-%5D%2B%5C%2F%5B%5Cw%5C-%5D%2B%5C%2F%5B%5Cw%5C-%5D%2B)%22&earliest=-1h&latest=now&sid=1603969504.2367540
The issue seems to be related to `health_sqs`
> Use a fixed string for source name

- server/lib/enrich/article.js
From MDN docs: 
> every acts like the "for all" quantifier in mathematics. In particular, for an empty array, it returns true. (It is vacuously true that all elements of the empty set satisfy any given condition.)
So instead `array && array.every` we need to have `array.length > 0 && array.every`
> ACC-754 fixed evil JS idiosyncrasy 

- package.json
This PR prepares next-syndication-api for v0.35.1 release
> chore: release next-syndication-api v0.35.1

- runbook.md
The previous version only had "GET the URL with API key" but no info where one finds the key or what format the contract ID needs to be in. Given this is intended for OpsCops / emergency use, I felt it was prudent to add those to be explicit.
> Update runbook to clarify how to call the API

- db/pg/index.js
Ticket: https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1108&projectKey=ACC&modal=detail&selectedIssue=ACC-798
Description:
Removes calls to `db.reload`, a function of [massive.js](https://massivejs.org/). 
We shouldn't be calling reload as it says in the documentation that [it is only necessary when changing the schema](https://massivejs.org/docs/connecting#reloading-the-api), which we do not do. Calling reload in the `else` block of `pg/index` meant that the database was being reloaded hundreds of times an hour, when changes aren't necessarily being made.  
A healthcare check on this package is constantly firing as a result of [a collision error that fires when a function has already been assigned](https://gitlab.com/dmfay/massive-js/-/blob/master/lib/database.js#L1 …
> ACC-798 Update massive implementation by removing use of `db.reload()`

- package.json
**This PR is dependent on https://github.com/Financial-Times/next-syndication-api/pull/292, which should be merged into the main branch first to implement the required changes for the `n-health` major upgrade, followed by a rebase of this branch onto the main branch (to pick up those changes).**
This PR upgrades the `n-es-client` dependency to v3.0.0 so that all of its Elasticsearch requests are directed to the new Elasticsearch v7 cluster.
It also upgrades the `n-express` version (which in turn upgrades the `next-metrics` version) so that metrics for requests to the Elasticsearch v7 cluster are captured correctly.
This app only uses `n-es-client` to make `get` and `mget` requests and the implementation applied here for those methods does not change between versions, meaning no further …
> Upgrade n-es-client 1.8.0 -> 3.0.0; n-express 21.0.0 -> 21.0.9

- package.json
After the release of this PR https://github.com/Financial-Times/next-syndication-api/pull/293, the metrics captured for Elasticsearch requests were still called `aws-elastic-v3-mget`. The expectation was that the upgrade of `next-metrics` to the most version version (v5.0.16) would mean that such Elasticsearch requests would be named `aws-elastic-v7-mget`.
This indicates that an older version of `next-metrics` is being used, and it seems the likely cause of this is via this app's dependency on `n-internal-tool`, which in turn has a dependency on an older version of `n-express`, which again in turn has a dependency on an older version of `next-metrics`.
This PR updates the `n-internal-tool` dependency to ensure that only the latest version of `next-metrics` is used by this app. …
> Upgrade n-internal-tool 7.0.0 -> 8.0.0

- config/production.yaml
- worker/sync/db-persist/mail-contributor.js
[Ticket](https://financialtimes.atlassian.net/browse/NOPS-602)
**TL;DR of the issue:** When an article by a freelancer gets syndicated, and email gets sent out to notify Someone that they need to pay extra money to the freelancer. These emails have stopped some time ago and need to be reinstated. 
**What we've done:**
- We are unable to see any of the logs in the `mail-contributor` file. We suspect this may be because the `logs` have been disabled in the config file. This PR enables the logs to see if that helps. 
- We are unsure if the function as a whole is getting called at all, and if yes, does it `return` at a first possible step (ie - none of the articles syndicated are written by freelancers). This PR adds `log.info` immediately after initiation to allow us to see if this function …
> NOPS-602 Enabled debugging for mail-contributor

- package.json
I need to release a new version of this project in order to update the `n-es-client` version used in the deployment of the `next-syndication-dl` project. 
Bumping to `0.36.0` instead of `0.35.2` as the `n-es-client` version update is not backwards compatible and I am not sure about the versioning standard used for this project but this feels right.
> Bump package.json version to 0.36.0

- .github/PULL_REQUEST_TEMPLATE.md
Following https://github.com/Financial-Times/incident-reports/issues/441 it became obvious that the special release / deploy procedure isn't documented visibly enough. To try to prevent similar issues in the future, this PR introduces a template that anyone raising the PR should follow - this should highlight the special procedure.
> ACC-1005 Added a PR template

- config/custom-environment-variables.yaml
- package.json
- test/worker/sync/db-persist/mail-contributor.spec.js
- worker/sync/db-persist/mail-contributor.js
[Ticket](https://financialtimes.atlassian.net/browse/NOPS-602)
Issue: Due to gmail security updates, gmail blocked `nodemailer` attempts to log in to sock-puppet send an email. As such, relevant alerts to pay the freelancers didn't get sent. 
This PR: 
- removes `nodemailer` functionality from `mail-contributor.js` and replaces it with [e-mail platform's POST send by address](https://ep.ft.com/docs/email-send-api/#api-Send-Post_send-by-address)
- you'll notice there's the ACCOUNTS_EMAIL as one of the recipients. I set that to my email address so that I get to see a copy of the email. Once I'm happy it looks good, I'll remove it. 
This PR does NOT:
- remove modules and google environment variables. My linter does not work for this repo and I am not confident to do this without a machine …
> NOPS-602 email client makeover for mail-contributor

- package.json
- worker/sync/db-persist/mail-contributor.js
Follow up to #305 
I merged before Tolu had a chance to comment and he pointed out that my `res.json()` fix will hit a race condition and suggested simplifying to `await res.json()`
This PR fixed the dodgy fix to `res.json()`.
https://financialtimes.atlassian.net/browse/NOPS-602
0.39.0 (because I already released the 0.38.0
I'm going to change this one to 0.39.0
https://github.com/Financial-Times/next-syndication-dl/pull/57
> NOPS-602 race condition fix

- .eslintrc.js
- db/pg/index.js
- package.json
- test/db/pg/index.spec.js
Reverts Financial-Times/next-syndication-api#309
The release has taken Syndication down with a massive spike of `error_message: self signed certificate`. Generally the recommended solution is to use `ssl = {rejectUnauthorised: false}` which is what we had to start with. 
I guess I don't need to worry about making a new release because `next-syndication-dl` `main` still looks for 0.38.1 and this PR reverts to that version?
> Revert "ACC-1106 SSL fine tune for DB connection"

- package.json
This has been annoying me for yonks. You make a commit, try to push, and then linter pipes up. So you either need to play the uncommit game or make a "fix typos" commit. I'm fed up of this.
It also bumps up the version do that DL can consume something that isn't buggy. 
no ticket. 
0.38.3
https://github.com/Financial-Times/next-syndication-dl/pull/59
> Make verify now runs on pre-commit as well

- db/pg/index.js
- health/db-sync-state.js
- health/error-spikes.js
- health/sqs.js
This PR
- adds a NODE_ENV info to our logs to help with [ACC-1106](https://financialtimes.atlassian.net/browse/ACC-1106). Dawn spotted that the bucket names are different between the calls that are failing vs those that are successful which imply that maybe the way our secrets are loaded may be related? 
- adds IDs to health checks because Dawn asked why things are green, and well, without the ID the connection to the data source is questionable (the graph doesn't work, so I'm guessing the values may not be correct either) and the checks aren't complaint anyway. See [FT Health Check standard document](https://docs.google.com/document/d/18hefJjImF5IFp9WvPAm9Iq5_GmWzI9ahlKSzShpQl1s/edit) for more info on health checks. 
n/a
This is logs and housekeeping, release isn't really needed.
> Housekeeping on logs and healthchecks

- package.json
- server/app.js
Changed the severity of error rate health check from 3 to 2
https://financialtimes.atlassian.net/browse/NOPS-920
0.38.4
https://github.com/Financial-Times/next-syndication-dl/pull/60
> NOPS-920. Changed default severity for error rate healthcheck

- README.md
Although this is not the most elegant solution to the "secrets don't automatically get set on review apps", this is quick way of letting people know how to silence the splunk errors. 
https://financialtimes.atlassian.net/browse/ACC-1106
Doc change, no new version needed.
> ACC-1106 Added explanation on how to deal with no_hba error

- .circleci/config.yml
- package.json
Following the branch name change, this PR handles associated chores as per https://github.com/Financial-Times/next/wiki/Migrating-apps-to-use-main-branch-(instead-of-master)
- upgrades n-gage
- updates CI yaml to use the new name
https://financialtimes.atlassian.net/browse/ACC-1169
> ACC-1169 main branch name change chores

- package.json
- server/app.js
- server/controllers/nonproduction/db-persist.js
- server/middleware/decode-session.js
Add an endpoint where we can trigger the db-persist workers so we can test they write to the database for upgrade work
n/a, part of syndication database upgrade work
n/a this is for testing code, won't run in production
n/a this is for testing code, won't run in production
> Db persist worker triggers

- server/middleware/get-licence-access-auth-token.js
- server/middleware/get-syndication-licence-for-user.js
- server/middleware/get-user-access-auth-token.js
- server/middleware/get-user-profile.js
- server/middleware/is-syndication-user.js
These middlewares have always resulted in unhandled promise rejections.
Express (v4) can't handle thrown errors in asynchronous routes and so
these errors weren't handled correctly.
The behaviour for unhandled rejections changed in Node.js 16, they used
to just log a warning but now they result in app crashes. This is why we
haven't had lots of app crashes until recently. See the [migration
notes](https://github.com/Financial-Times/next/wiki/Node-14-%26-16-Migration-Guide#breaking-changes-to-look-out-for)
I'm now handling all the promise rejections properly by passing the
error onto the next route rather than rethrowing it. This should protect
the app from going down if there's an error in the routes.
No ticket but it relates to [incident …
> Prevent app crashes caused by unhandled rejections

- server/middleware/get-syndication-licence-for-user.js
Description
These middlewares have always resulted in unhandled promise rejections.
Express (v4) can't handle thrown errors in asynchronous routes and so
these errors weren't handled correctly.
The behaviour for unhandled rejections changed in Node.js 16, they used
to just log a warning but now they result in app crashes. This is why we
haven't had lots of app crashes until recently. See the migration
notes
I'm now handling all the promise rejections properly by passing the
error onto the next route rather than rethrowing it. This should protect
the app from going down if there's an error in the routes.
Ticket
No ticket but it relates to [incident 1554](https://financialtimes.slack.com/archives/C03HF9PG7A9).
> Prevent app crashes caused by unhandled rejections 2

- server/lib/logger.js
[This splunk query](https://financialtimes.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22heroku%22%20source%3D%22%2Fvar%2Flog%2Fapps%2Fheroku%2Fft-next-syndication-api.log%22%20%7C%20spath%20message%20%7C%20regex%20message%3D%22creating%20new%20DB%20instance%20with%20options%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-1w&latest=now&sid=1659948508.2839421) shows that we are loggin db data(username and connection uri which includes the password).
This PR will tend to mask user_name and uri  data that is logged in next-syndication-api logger.
[Jira-ticket](https://financialtimes.atlassian.net/browse/ACC-1833)
> ACC-1833-Update logger to mask db uri and user_name

- package-lock.json
- package.json
- server/lib/logger.js
This to work on [this ticket ](https://financialtimes.atlassian.net/browse/ACC-1943?atlOrigin=eyJpIjoiN2U5ZDIxZmExOWVmNDg2Y2JiMGY2Mzg2YWNhMDA4MTgiLCJwIjoiaiJ9). In order to remove `NPM_CONFIG_PRODUCTION` from vault which was required, but fixed in n-gage v9. 
no longer supporting older versions of node and npm (this project does not use them)
> chore(): bump n-gage to v9.x

- app.json
- package-lock.json
- package.json
Buildpacks are responsible for transforming deployed code into a slug, which can then be executed on a dyno. Buildpacks are composed of a set of scripts, and depending on the programming language, the scripts will retrieve dependencies, output generated assets or compiled code, and more. This output is assembled into a slug by the [slug compiler](https://devcenter.heroku.com/articles/slug-compiler).
Heroku’s support buildtsacks such as Ruby, Python, Java, Clojure, Node.js, Scala, Go and PHP out of the box
By default, these buildpacks will be searched in an order until a match is detected and used to compile your app. If the build succeeds, the detected buildpack will be permanently set for future pushes to your application as if you had run heroku `buildpacks:set` e.g `heroku …
> ACC-2020-Chore: Build stack migration from 18=>22

- package.json
This PR is bumping the `package.json` version to trigger a new release as part of [this PR](https://github.com/Financial-Times/next-syndication-api/pull/403)
[Ticket](https://financialtimes.atlassian.net/browse/ACC-2020)
> ACC-2020- Fix: Bumping up package version

- package.json
This PR applies the release changes I forgot to include as part of https://github.com/Financial-Times/next-syndication-api/pull/411. It looks like the release will also include some preceding commits but that seems okay.
The reason this PR skips from 0.41.4 to 0.41.6 (and misses 0.41.5) is because that version was released [here](https://github.com/Financial-Times/next-syndication-api/releases/tag/v0.41.5), although without the corresponding change to the `package.json`.
N/A
0.41.6
https://github.com/Financial-Times/next-syndication-dl/pull/120
> Increment package.json version 0.41.4 -> 0.41.6

- .github/PULL_REQUEST_TEMPLATE.md
This PR corrects a reference to the `package.json` file in the `.github/PULL_REQUEST_TEMPLATE.md` to make clearer where the new version number should live.
N/A
N/A
N/A
> Correct reference to package.json in .github/PULL_REQUEST_TEMPLATE.md

- package.json
- server/lib/reformat-salesforce-contract.js
If the contract data is coming all lowercase from Salesforce, capitalize the first letter before saving to the DB. This is because of the enum_time_period in next-syndication-db-schema, which only accepts uppercase: https://github.com/Financial-Times/next-syndication-db-schema/blob/main/schema.syndication.base/type/enum_time_period.sql
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-2118)
> ACC-2118 Capitalize first letter of time period before save to DB

- server/lib/download/index.js
The original purpose of the ticket was to stop sending so many Postgres logs every time a user downloads an article. However, while at it, we also discovered some of these logs contained PII data. **This PR removes the PII data from the logs.**
**Investigation**:
We discovered that the 600k Postgres logs happen only when a user downloads an article the first time. If they download the same article a second time then the number of logs is reduced to about 1k. 
We believe this is happening because of this trigger: https://github.com/Financial-Times/next-syndication-db-schema/blob/main/schema.syndication.computed/trigger/contract_asset_register_data.sql#L25
this is the first log that shows up when the series of 600k logs occurs:
2022-12-19T15:07:22.000000+00:00 app[postgres.2622403]: [WHITE] …
> ACC-2132 Remove PII Data from Postgres logs

- config/default.yaml
All the base tables need to be added to the backups for the computed tables to be restored properly.
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-2137)
> ACC-2137 Add base tables to backup

- package-lock.json
- package.json
- server/lib/get-salesforce-contract-by-id.js
We had a small incident https://financialtimes.slack.com/archives/C042NBBTM/p1673609082333779 where users on a specific contract couldn't see the Syndication Icons. All we had was a bunch of `NullApexResponse`. 
Originally we thought that the best thing to do was to add a default value to `dontThrow` (which is defined as an argument of this function, but isn't actually used in any places where the function is called) - but there wasn't a clear answer as to what the default should be. 
So what we're doing is enhancing the error so that it's a bit clearer as to what's happening "under the hood" and offer a quick fix to whoever is looking at the logs. Hopefully if and when we actually get to see `NullApexResponse` again, we will also have more information to allow us to make an informed …
> ACC-2208 enhance NullApexResponse error

- package-lock.json
- package.json
- server/lib/get-contract-by-id.js
- server/middleware/get-contract-by-id-from-session.js
Due to an error with salesforce data, there may be cases in which we receive the assets of a contract as null, causing the code to break and not allow users to enter.
[Slack](https://financialtimes.slack.com/archives/C3LRB6JCE/p1678197718180599)
[ACC-2264](https://financialtimes.atlassian.net/browse/ACC-2264)
0.41.10
[ACC-2264]: https://financialtimes.atlassian.net/browse/ACC-2264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ACC-2264: prevent error about possible null errors in the assets

- package-lock.json
- package.json
- test/api/download-by-content-id-api.spec.js
The API test should check that when the user clicks on “downloaded items”, they can click on “Download” and a download will start
[ACC-2270](https://financialtimes.atlassian.net/browse/ACC-2270)
0.41.12
[ACC-2270]: https://financialtimes.atlassian.net/browse/ACC-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ACC-2270: add api test for download content syndication

- README.md
Add instructions about how to run syndication API against prod in local.
remove duplicated documentation
[ACC-2285](https://financialtimes.atlassian.net/browse/ACC-2285)
[ACC-2285]: https://financialtimes.atlassian.net/browse/ACC-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ACC-2285: tidy documentation and add how to run agains prod db

- runbook.md
we’ve had [a report](https://financialtimes.slack.com/archives/C042NBBTM/p1674485188998109) that a user is unable to access the syndication tools in their browser.
we solved executing a script against syndication database to update the new guid of the user and we update the runbook doc to help with this possible issue in the future
[ACC-2207](https://financialtimes.atlassian.net/browse/ACC-2207)
[ACC-2207]: https://financialtimes.atlassian.net/browse/ACC-2207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ACC-2207: update runbook

- package-lock.json
- package.json
- server/app-dl.js
- server/app.js
Part of [CPREL-649](https://financialtimes.atlassian.net/browse/CPREL-649). The n-express update in this PR is safe as it drops Node.js 14 support and disables Sentry by default.
[CPREL-649]: https://financialtimes.atlassian.net/browse/CPREL-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Replace Sentry with Reliability Kit Crash Handler

- .circleci/config.yml
- .toolkitrc.yml
- Procfile
- package-lock.json
- package.json
We're invited to embrace progress and enhance our estate by upgrading them to Node 18. This upgrade brings exciting improvements and features. 
This PR migrates the app to use node 18.
Our dedicated platform team has meticulously developed a migration script, which can be found [here](https://github.com/Financial-Times/platform-scripts/blob/main/upgrade-node-18/README.md)
[Ticket](https://financialtimes.atlassian.net/browse/ACC-2425)
> chore: update to node 18

- package-lock.json
- package.json
I have noticed there are inconsistent versions in the release package.json and release version. This PR aimed at aligning the package.json version to align with the release version for consistency going forward
[DL PR](https://github.com/Financial-Times/next-syndication-dl/pull/141)
> chore:Alignment of package.json version and release version

- db/pg/column_mappings/contracts.js
- db/table_schemas/contracts.js
- package.json
- server/controllers/get-contract-by-id.js
- server/lib/get-contract-by-id.js
We need to add new current period date columns in contracts table using the salesforce new payload fields (orders).
This way we can modify after the query that counts the “current_downloads” in contract_asset_register_data and contract_asset_data tables in syndication database.
we need to check that this “current_period_start_date” and “current_period_end_date” are updated when the current period change.
We have a 24h cronjob that calls the salesforce endpoint and we should check if the current period has changed checking the period status, we should always update this columns with the dates of the current period to keep it updated. 
[ACC-2510](https://financialtimes.atlassian.net/browse/ACC-2510)
1.3.0
pending
[ACC-2510]: https://financialtimes.atlassian.net/browse/ACC-2510?atlOrigin=eyJp …
> ACC-2510: add current period start and endate for multiyears contracts

- package.json
- server/middleware/get-user-access-auth-token.js
The automatic redirect would return a url of `www.ft.com` without the `auth_token`. Setting redirect to `manual` gives us the correct url location in the headers with the `auth_token`. This fix addresses the [No User Access Token errors ](https://financialtimes.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22heroku%22%20source%3D*next-syndication*%20level%3Derror&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-24h&latest=now&sid=1696338500.32133489) being logged
https://financialtimes.atlassian.net/browse/ACC-2702
1.4.1
TBD.. 1.4.0 needs to be released first
> ACC-2702 Fix user access token error

- server/middleware/get-user-access-auth-token.js
`.split()` method was erroring when `authResLocation` is null
1.4.2
https://github.com/Financial-Times/next-syndication-dl/pull/152
> Add a fallback option for authRes.location to avoid error

- .toolkitrc.yml
- README.md
- health/db-backups.js
- health/db-sync-state.js
- runbook.md
- toolkit/start/index.js
- Updates all readme/doc mentions of vault to doppler
- Sets up doppler task in toolkit so it uses doppler for local development
- Uses doppler instead of vault for the `SyndicationAPITask`
[ACC-2770](https://financialtimes.atlassian.net/browse/ACC-2770)
[ACC-2770]: https://financialtimes.atlassian.net/browse/ACC-2770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Setup doppler

- package-lock.json
- package.json
Using an old version of archiver breaks the archiving of vtt caption files on video downloads.
The file was being produced but the contents was empty.
This was reported in ft-next-support https://financialtimes.slack.com/archives/C042NBBTM/p1699611597255009
Scanning the breaking changes in the archiver change log most of the breaking changes are only to drop node versions.
I have done my best to assess the other changes and I am hopeful that they wont impact us but I can't be completely sure.
> Bump archiver version to fix captions issue

- server/lib/download/video.js
The caption files are empty so we want to see what exists at this point when running in production as in local the contents exists
> Add logging when appending captions

- package-lock.json
- package.json
The version of next-metrics used by next-syndication-api / next-syndication-dl is not up to date so we are getting alerts when users try and download an article with a renditions video included.
[ACC-2799](https://financialtimes.atlassian.net/browse/ACC-2799)
2.0.4
[ACC-2799]: https://financialtimes.atlassian.net/browse/ACC-2799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ACC-2799: Update n-express to use latest metrics

- package.json
- server/controllers/get-contract-by-id.js
- server/lib/get-contract-by-id.js
While testing some changes I realised that the `current_start_date` and `current_end_date` in a multiyear contract were not being populated in the database. While comparing the code and the salesforce contract I realised that we were looking for orders with `status:Active` while the contract stated `status:Activated`. I asked the Salesforce team and there was a miscommunication, while we were given contracts with order status of `Active` to test with, in production it has always been `Activated`. The salesforce team is currently assessing business impact of this.
An additional check has been implemented to make sure that the current date is in between the activated order's start and end date as per recommendation from the Salesforce team.
2.0.5 …
> Orders status bug Active -> Activated

- package.json
- server/controllers/get-contract-by-id.js
- server/lib/get-contract-by-id.js
bug in: server/lib/get-contract-by-id.js line 107
```
contract = reformatSalesforceContract(contract);
```
Since the contract returned by `getSalesforceContractByID(contractId);` assigned to the variable ` contract` was being reassigned by the contract returned from `reformatSalesforceContract(contract);` the `orders` object that came from SalesForce but is not needed in our database was being lost. Therefore when we did:
```
const activeOrder = contract.orders.find(order => order.status === 'Activated' && new Date(order.startDate) <= currentTimeInMilliseconds && new Date(order.endDate) >= currentTimeInMilliseconds);
```
No activeOrder was being found.
This PR makes variable names more explicit and reuses them less to avoid issues from mutations. …
> bugfix: make variables more explicit and reuse them less

- package.json
- test/worker/sync/db-persist/spoor-publish.spec.js
- worker/sync/db-persist/spoor-publish.js
This PR updates the usage of `new Buffer` which will output the following warning:
> (node:9017) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
- [Stack Overflow: DeprecationWarning: Buffer() is deprecated due to security and usability issues when I move my script to another server](https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues#answer-52257416)
```js
new Buffer(number)            // Old
Buffer.alloc(number)          // New
new Buffer(string)            // Old
Buffer.from(string)           // New
new Buffer(string, encoding)  // Old
Buffer.from(string, encoding) // New
new …
```
> Update deprecated Buffer usage

- .eslintrc.js
- package.json
- server/controllers/get-contract-by-id.js
- server/lib/get-contract-by-id.js
Getting the activeOrder's start and end date is something that is specific to multiyear contracts. There will sometimes not be an active order so we should expect for these values to be undefined. Added optional chaining to avoid errors.
eslint's ecmaVersion was increased so that the linter supports optional chaining
v2.0.8
> BugFix: Add optional chaining to activeOrders

- .snyk
- package-lock.json
- package.json
Usage of Snyk at the FT is deprecated.We will not be renewing our licence after 19th December 2024, therefore we are removing all references to it.
> ACC-3368 Remove Snyk References

- CODEOWNERS
This PR updates the CODEOWNERS file to reflect its new ownership.
[LIF-2: Admin for setting up Lifecycle team's resources](https://financialtimes.atlassian.net/jira/software/c/projects/LIF/boards/2009/?selectedIssue=LIF-2)
N/A
N/A
N/A
> Update CODEOWNERS to @financial-times/cp-customer-lifecycle

- .circleci/config.yml
- .toolkitrc.yml
- package-lock.json
- package.json
update node version to 22.x and npm to 10.x. Also bump the version of the pakcage itself to v3.0.0
[LIF-30](https://financialtimes.atlassian.net/browse/LIF-30)
v3.0.0
[LIF-30]: https://financialtimes.atlassian.net/browse/LIF-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update node version to 22.x and npm to 10.x

- .circleci/config.yml
- .toolkitrc.yml
- package-lock.json
- package.json
Rollback to node 18 because the users cannot see the republish icon.
[LIF-30](https://financialtimes.atlassian.net/browse/LIF-30)
[LIF-30]: https://financialtimes.atlassian.net/browse/LIF-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert "update node engine version to 22.x and npm to 10.x"

- .circleci/config.yml
- .gitignore
- .toolkitrc.yml
- package-lock.json
- package.json
- toolkit/logs/.toolkitrc.yml
- toolkit/logs/index.js
- toolkit/start/.toolkitrc.yml
- toolkit/start/index.js
This PR is migrating the package to dotcom toolkit v4.x.x
[Jira Ticket ](https://financialtimes.atlassian.net/browse/LIF-100)
> chore: Toolkit migration to v4.x.x

- package-lock.json
- package.json
- server/lib/logger.js
This migrates the system to use Reliability Kit logger instead of the deprecated n-mask-logger. There are a few things in the custom `Logger` class in this system that are handled by Reliability Kit logger (e.g. baseLogData), however, I wanted to keep this simple and just extract the old dependency.
At some point in future you may want to refactor/reassess the need for such a comprehensive helper.
> Migrate to Reliability Kit logger

- runbook.md
Update runbook to include instructions on how to force refresh a contract. This includes a note on the `first line of troubleshooting` which is what OPS team usually focus on. The note mentions a secure note with instructions, the instructions are essentially the same as the ones in `### Check the details and sync a specific contract with the latest SalesForce` but they also include the secret key.
> Update runbook.md to include contract refresh info

- runbook.md
OPS requested to just make references to their team in the firstline of troubleshooting
> Update runbook.md – remove OPS references from second line troubleshooting
